[package]
name = "egomoose/tween-promise"
description = "https://github.com/EgoMoose/tween-promise"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
ignore = ["test", "assets"]

[dependencies]
Promise = "evaera/promise@4.0.0"